const DATA = [
  {
    delivery_id: 3354,
    delivery_uid: "8aded59b-fe76-4068-805c-387c8b12923f",
    delivery_reference: "32457340",
    delivery_addresse: "4 clos de la motte louvet",
    delivery_city: "GOUVIEUX",
    delivery_postcode: "60270",
    delivery_note:
      "Merci de livrer la Hotte WISE90BK + le filtre 18909 au nom de Deverweraere (voir mon mail du 16/06/22)\r\net sortir du bloc NOB pour stock la hotte BELTBFL80 pos. 15",
    magasin_name: "AVIVA ST MAXIMIN",
    magasin_short_name: "ASM",
    client_address: "4 clos de la motte louvet",
    client_city: "GOUVIEUX",
    client_postcode: "60270",
    person_gender: "Mme.",
    person_prenom: "Sylvie",
    person_nom: "BANGUIO",
    person_mobile: "(+33) 669-565-451",
    person_email: "sbanguio@gmail.com",
    event_description: "4 clos de la motte louvet 60270 GOUVIEUX",
    event_title: "BANGUIO Sylvie",
    event_classname: "#007bff",
    delivery_filename:
      "C:\\wamp64\\www\\ndg\\storage\\app/delivery/2022-09-26_pWxlgAkm7zylyWIW.pdf",
    delivery_filename_ext: "pdf",
  },
  {
    delivery_id: 3658,
    delivery_uid: "5646f6b4-6219-4d9e-b8c0-c73699e53428",
    delivery_reference: "32684742",
    delivery_addresse: "1 rue du pont de baillet",
    delivery_city: "BAILLET EN FRANCE",
    delivery_postcode: "95560",
    delivery_note: null,
    magasin_name: "ECOCUISINE ST BRICE",
    magasin_short_name: "ESF",
    client_address: "1 rue du pont de baillet",
    client_city: "BAILLET EN FRANCE",
    client_postcode: "95560",
    person_gender: "Mme.",
    person_prenom: "STEPHANIE",
    person_nom: "MOHIDEEN",
    person_mobile: "(+33) 651-029-083",
    person_email: "stephanie_mohideen@hotmail.fr",
    event_description: "1 rue du pont de baillet 95560 BAILLET EN FRANCE",
    event_title: "MOHIDEEN STEPHANIE",
    event_classname: "#007bff",
    delivery_filename: null,
    delivery_filename_ext: null,
  },
  {
    delivery_id: 3760,
    delivery_uid: "bfb8b2ab-1384-47e9-af5e-e1a4af84ff39",
    delivery_reference: "2000715",
    delivery_addresse: "2 rue de la roseraie",
    delivery_city: "abbecourt",
    delivery_postcode: "02300",
    delivery_note: null,
    magasin_name: "ixina rambouillet",
    magasin_short_name: "ixi",
    client_address: "2 rue de la roseraie",
    client_city: "abbecourt",
    client_postcode: "02300",
    person_gender: "M.",
    person_prenom: "Fidel",
    person_nom: "Llorente",
    person_mobile: "(+33) 689-509-679",
    person_email: null,
    event_description: "2 rue de la roseraie 02300 abbecourt",
    event_title: "Llorente Fidel",
    event_classname: "#007bff",
    delivery_filename:
      "C:\\wamp64\\www\\ndg\\storage\\app/delivery/2022-09-26_ElTfgcPwirTHpz84.pdf",
    delivery_filename_ext: "pdf",
  },
  {
    delivery_id: 3837,
    delivery_uid: "97e1ca07-82a2-4dee-a54a-d663b5644a51",
    delivery_reference: "4183769.00",
    delivery_addresse: "195 rue des Martyrs",
    delivery_city: "VENETTE",
    delivery_postcode: "60280",
    delivery_note:
      "Merci de retirer du bloc la crédence ref NV1657 pour stock magasin\r\nLe Lave-vaisselle CANDY en stock à la plateforme  ref CDIN4D530PBE est à livrer aux clients également (voir e-mail du 24/03/22)",
    magasin_name: "AVIVA ST MAXIMIN",
    magasin_short_name: "ASM",
    client_address: "195 rue des Martyrs",
    client_city: "VENETTE",
    client_postcode: "60280",
    person_gender: "M.",
    person_prenom: "Flora",
    person_nom: "ABREU / OGET",
    person_mobile: "(+33) 671-505-995",
    person_email: "floraabreu@outlook.com",
    event_description: "195 rue des Martyrs 60280 VENETTE",
    event_title: "ABREU / OGET Flora",
    event_classname: "#007bff",
    delivery_filename:
      "C:\\wamp64\\www\\ndg\\storage\\app/delivery/2022-09-26_vAiE0LMn8PQ2j1ZB.pdf",
    delivery_filename_ext: "pdf",
  },
  {
    delivery_id: 3848,
    delivery_uid: "d24c2ce1-3393-40fb-b08a-7db93f39d044",
    delivery_reference: "32657755",
    delivery_addresse: "1 rue therdonne",
    delivery_city: "Beauvais",
    delivery_postcode: "60000",
    delivery_note: "220710/DESCHAMPS/MC",
    magasin_name: "ECOCUISINE",
    magasin_short_name: "ECO",
    client_address: "5 bis rue du moulin",
    client_city: "noailles",
    client_postcode: "60430",
    person_gender: "Mme.",
    person_prenom: "MELANIE",
    person_nom: "DESCHAMPS",
    person_mobile: "(+33) 689-258-579",
    person_email: "deschamps96@gmail.com",
    event_description: "1 rue therdonne 60000 Beauvais",
    event_title: "DESCHAMPS MELANIE",
    event_classname: "#b87e17",
    delivery_filename: null,
    delivery_filename_ext: null,
  },
  {
    delivery_id: 3909,
    delivery_uid: "bf095082-3c17-4f7a-b013-2bf280932280",
    delivery_reference: "LA PART DES ANGES",
    delivery_addresse: "74 Avenue du General De Gaulle",
    delivery_city: "VERNEUIL EN HALATTE",
    delivery_postcode: "60550",
    delivery_note: null,
    magasin_name: "CUIZEN",
    magasin_short_name: "CZN",
    client_address: "74 Avenue du General De Gaulle",
    client_city: "VERNEUIL EN HALATTE",
    client_postcode: "60550",
    person_gender: "M.",
    person_prenom: "Jacques et Astrid",
    person_nom: "LA PART DES ANGES (PEUTAT/STIERS)",
    person_mobile: "(+33) 781-622-168",
    person_email: "lapartdesanges74@free.fr",
    event_description:
      "74 Avenue du General De Gaulle 60550 VERNEUIL EN HALATTE",
    event_title: "LA PART DES ANGES (PEUTAT/STIERS) Jacques et Astrid",
    event_classname: "#007bff",
    delivery_filename:
      "C:\\wamp64\\www\\ndg\\storage\\app/delivery/2022-09-26_ZgyDV9GongK4OSGS.pdf",
    delivery_filename_ext: "pdf",
  },
  {
    delivery_id: 3927,
    delivery_uid: "230b270d-0798-47f8-9483-31b815c7d00f",
    delivery_reference: "AR N° 32816293",
    delivery_addresse: "1 RUE PIERRE ET MARIE CURIE",
    delivery_city: "BEAUVAIS",
    delivery_postcode: "60000",
    delivery_note: "RAPATRIEMENT",
    magasin_name: "BUT BEAUVAIS",
    magasin_short_name: "BB",
    client_address: "14 bis, Grande Rue",
    client_city: "MILLY SUR THERAIN",
    client_postcode: "60118",
    person_gender: "Mme.",
    person_prenom: "Cristel",
    person_nom: "WILMART",
    person_mobile: "(+33) 631-680-109",
    person_email: "wilmart.cristel@gmail.com",
    event_description: "1 RUE PIERRE ET MARIE CURIE 60000 BEAUVAIS",
    event_title: "WILMART Cristel",
    event_classname: "#b87e17",
    delivery_filename: null,
    delivery_filename_ext: null,
  },
  {
    delivery_id: 3884,
    delivery_uid: "643c0f51-ed71-4ba4-9165-538a0322debc",
    delivery_reference: "32458027",
    delivery_addresse: "1 rue du pot de baillet",
    delivery_city: "BAILLET EN FRANCE",
    delivery_postcode: "95560",
    delivery_note: null,
    magasin_name: "ECOCUISINE ST BRICE",
    magasin_short_name: "ESF",
    client_address: "1 rue du pot de baillet",
    client_city: "BAILLET EN FRANCE",
    client_postcode: "95560",
    person_gender: "Mme.",
    person_prenom: "MARINA",
    person_nom: "GIRAUDEAU FORTES",
    person_mobile: "(+33) 652-373-991",
    person_email: "marinagiraudeau@hotmail.fr",
    event_description: "1 rue du pot de baillet 95560 BAILLET EN FRANCE",
    event_title: "GIRAUDEAU FORTES MARINA",
    event_classname: "#007bff",
    delivery_filename: null,
    delivery_filename_ext: null,
  },
  {
    delivery_id: 3405,
    delivery_uid: "e7de1115-194f-48fe-96ad-9a0b52be68a6",
    delivery_reference: "32468375",
    delivery_addresse: "316 Rue Pennellier",
    delivery_city: "Laneuvilleroy",
    delivery_postcode: "60190",
    delivery_note: "POSE 03.10\r\nNV 203  X2 A CONTREMARQUER DRU",
    magasin_name: "AVIVA COMPIEGNE",
    magasin_short_name: "AVC",
    client_address: "316 Rue Pennellier",
    client_city: "Laneuvilleroy",
    client_postcode: "60190",
    person_gender: "M.",
    person_prenom: "Brigitte",
    person_nom: "Marchal",
    person_mobile: "(+33) 660-521-201",
    person_email: null,
    event_description: "316 Rue Pennellier 60190 Laneuvilleroy",
    event_title: "Marchal Brigitte",
    event_classname: "#007bff",
    delivery_filename: null,
    delivery_filename_ext: null,
  },
  {
    delivery_id: 3428,
    delivery_uid: "1f5bfdbe-36df-439c-89df-fc74f1b1fd5c",
    delivery_reference: "32527246",
    delivery_addresse: "126 route des flandres",
    delivery_city: "pont ste maxence",
    delivery_postcode: "60700",
    delivery_note: null,
    magasin_name: "BUT CREIL",
    magasin_short_name: "BC",
    client_address: "126 route des flandres",
    client_city: "pont ste maxence",
    client_postcode: "60700",
    person_gender: "Mme.",
    person_prenom: "Manon",
    person_nom: "Fontaine armand",
    person_mobile: "(+33) 658-655-357",
    person_email: null,
    event_description: "126 route des flandres 60700 pont ste maxence",
    event_title: "Fontaine armand Manon",
    event_classname: "#007bff",
    delivery_filename: null,
    delivery_filename_ext: null,
  },
];

export default DATA;
